name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          event: deploy
          message: test
          resourceid: 952
